version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - angular-net

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - angular
    networks:
      - angular-net

networks:
  angular-net:
    driver: bridge
